version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-ndk
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #      - run:
      #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
      #         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          pre:
             echo y | android update sdk --no-ui --all --filter "platform-tools, tools"
             echo y | android update sdk --no-ui --all --filter "android-24, build-tools-25.0.2"
             echo y | android update sdk --no-ui --all --filter "extra-android-m2repository"
             echo y | android update sdk --no-ui --all --filter "extra-android-support"
          command: chmod +x ./gradlew
                   chmod +x gradlew
                   ./gradlew androidDependencies
          #./gradlew --gradle-version 5.4.1 --distribution-type all
          #command: ./gradlew androidDependencies
          #sudo chmod +x ./gradlew  #ref: link   https://discuss.circleci.com/t/gradle-permission-denied-in-circle-2-0-exited-with-code-126/26741

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test


      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples

      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
                path: app/build/outputs/apk/debug/
                destination: artifact-file
